In [1]:
# Design and implement Implement Union, Intersection, Complement and Difference operations on fuzzy sets.
# Also create fuzzy relations by Cartesian product of any two fuzzy sets and perform max-min composition on
# any two fuzzy relations.

In [3]:
import numpy as np
def fuzzy_union(A, B):
    return np.maximum(A, B)

def fuzzy_intersection(A, B):
    return np.minimum(A, B)

def fuzzy_complement(A):
    return 1 - A

def fuzzy_difference(A, B):
    return np.minimum(A, 1 - B)

In [5]:
def cartesian_product(A, B):
    return np.outer(A, B)

def max_min_composition(R, S):
    return np.max(np.minimum(R[:, np.newaxis, :], S[np.newaxis, :, :]), axis=2)

In [7]:
# Define two fuzzy sets
A = np.array([0.2, 0.5, 0.8])
B = np.array([0.3, 0.6, 0.7])

# Perform operations
union_result = fuzzy_union(A, B)
intersection_result = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
difference_A_B = fuzzy_difference(A, B)

# Display results
print("Union:", union_result)
print("Intersection:", intersection_result)
print("Complement of A:", complement_A)
print("Difference A - B:", difference_A_B)

Union: [0.3 0.6 0.8]
Intersection: [0.2 0.5 0.7]
Complement of A: [0.8 0.5 0.2]
Difference A - B: [0.2 0.4 0.3]


In [9]:
# Define two fuzzy sets for Cartesian product
C = np.array([0.1, 0.4, 0.9])
D = np.array([0.2, 0.5, 0.8])

# Create fuzzy relations using Cartesian product
R = cartesian_product(A, B)
S = cartesian_product(C, D)

# Perform max-min composition
composition_result = max_min_composition(R, S)

# Display results
print("Fuzzy Relation R (Cartesian product of A and B):")
print(R)
print("Fuzzy Relation S (Cartesian product of C and D):")
print(S)
print("Max-Min Composition of R and S:")
print(composition_result)

Fuzzy Relation R (Cartesian product of A and B):
[[0.06 0.12 0.14]
 [0.15 0.3  0.35]
 [0.24 0.48 0.56]]
Fuzzy Relation S (Cartesian product of C and D):
[[0.02 0.05 0.08]
 [0.08 0.2  0.32]
 [0.18 0.45 0.72]]
Max-Min Composition of R and S:
[[0.08 0.14 0.14]
 [0.08 0.32 0.35]
 [0.08 0.32 0.56]]
